insert into Phrases (id,phrases,author) values(1,'A Informática é uma ciência exotérica','Gabriella Eloy');
insert into Phrases (id,phrases,author) values(2,'Ciência é conhecimento organizado. Sabedoria é vida organizada','Immanuel Kant');
insert into Phrases (id,phrases,author) values(3,'O aspecto mais triste da vida de hoje é que a ciência ganha em conhecimento mais rapidamente que a sociedade em sabedoria','Isaac Asimov');
insert into Phrases (id,phrases,author) values(4,'Toda a nossa ciência, comparada com a realidade, é primitiva e infantil – e, no entanto, é a coisa mais preciosa que temos','Albert Einstein');
insert into Phrases (id,phrases,author) values(5,'Todo grande progresso da ciência resultou de uma nova audácia da imaginação','John Dewey');
insert into Phrases (id,phrases,author) values(6,'A ciência se compõe de erros que, por sua vez, são os passos até a verdade.','Julio Verne');
insert into Phrases (id,phrases,author) values(7,'Existem muitas hipóteses em ciência que estão erradas. Isso é perfeitamente aceitável, elas são a abertura para achar as que estão certas','Carl Sagan');
insert into Phrases (id,phrases,author) values(8,'A ciência conhece um único comando: contribuir com a ciência','Bertold Brecht');
insert into Phrases (id,phrases,author) values(9,'A grande tragédia da ciência: o massacre de uma bela hipótese por parte de um horrível fato','Thomas Huxley');
insert into Phrases (id,phrases,author) values(10,'O começo de todas as ciências é o espanto de as coisas serem o que são','Aristóteles');
insert into Phrases (id,phrases,author) values(11,'Esta é a essência da ciência: faça uma pergunta impertinente e cairá no caminho da resposta pertinente','J. Bronowski');
insert into Phrases (id,phrases,author) values(12,'Em ciência não existe um erro tão grosseiro que, amanhã ou depois, sob alguma perspectiva, não pareça profético','Jean Rostand');
insert into Phrases (id,phrases,author) values(13,'A ciência é o melhor instrumento para medir a nossa ignorância','Paolo Mantegazza');
insert into Phrases (id,phrases,author) values(14,'A vaidade de muita ciência é prova de pouco saber','Marquês de Maricá');
insert into Phrases (id,phrases,author) values(15,'A pesquisa básica é como atirar uma flecha para o ar e, onde ela cair, pintar um alvo','Homer Adkins Burton');
insert into Phrases (id,phrases,author) values(16,'O homem gosta de surpreender-se, e isso é a semente da ciência','Gabriella Eloy');
insert into Phrases (id,phrases,author) values(17,'A menor distancia entre dois pontos é a ciência','Adan Fernandes da Silva');
insert into Phrases (id,phrases,author) values(18,'Quando o PC foi lançado, as pessoas sabiam que era algo importante.','Bill gates');
insert into Phrases (id,phrases,author) values(19,'O perigo real não é de computadores começarem a pensar como homens, mas de homens começarem a pensar como computadores.','sydney j. harris');
insert into Phrases (id,phrases,author) values(20,'As máquinas me surpreendem muito frequentemente.','Alan Turing');
insert into Phrases (id,phrases,author) values(22,'Eu acredito que às vezes são as pessoas que ninguém espera nada que fazem as coisas que ninguém consegue imaginar.','Alan Turing');
insert into Phrases (id,phrases,author) values(23,'Eu não fico muito impressionado com argumentos teológicos, independentemente daquilo que eles estão sendo usado para apoiar. Esses argumentos frequentemente se revelaram insatisfatórios no passado.','Alan Turing');
insert into Phrases (id,phrases,author) values(24,'A vida sem ciência é uma espécie de morte.','Sócrates');
insert into Phrases (id,phrases,author) values(25,'A ciência descreve as coisas como são; a arte, como são sentidas, como se sente que são.','Fernando Pessoa');
insert into Phrases (id,phrases,author) values(26,'A televisão é a maior maravilha da ciência a serviço da imbecilidade humana.','Barão de Itararé');
insert into Phrases (id,phrases,author) values(28,'A ciência é o grande antídoto do veneno do entusiasmo e da superstição','Adam Smith');
insert into Phrases (id,phrases,author) values(29,'A ciência poderá ter encontrado a cura para a maioria dos males, mas não achou ainda o remédio para o pior de todos: a apatia dos seres humanos.','Helen Keller');
insert into Phrases (id,phrases,author) values(30,'A ciência nunca resolve um problema sem criar pelo menos outros dez.','George Bernard Shaw');
insert into Phrases (id,phrases,author) values(31,'Não se conhece completamente uma ciência enquanto não se souber da sua história.','Auguste Comte');